name: App Builder
on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    release:
        strategy:
            fail-fast: false
            matrix:
                platform: [windows-latest]
                include:
                    - os: windows-latest
                      rust_target: x86_64-pc-windows-msvc
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # for projects that use labels and PRs,
            # try https://github.com/mikepenz/release-changelog-builder-action instead
            # TODO: use API to collect commit messages
            - name: Build Changelog
              id: build_changelog
              run: echo "changelog=- ADD CHANGELOG" >> $GITHUB_OUTPUT

            - name: Node.js setup
              uses: actions/setup-node@v3
              # NOTE: enterprise developers may hard code a version
              with:
                  node-version: latest
                  # node-version-file: '.nvmrc'

            - name: Install Rust (Stable)
              run: curl https://sh.rustup.rs -sSf | sh -s -- -y

            - name: Install app dependencies from lockfile and build web
              # NOTE: comment out && yarn build if frontend does not have build script
              run: npm install --frozen-lockfile && npm run build

            - name: Build the app
              uses: tauri-apps/tauri-action@v0

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  # tauri-action replaces \_\_VERSION\_\_ with the app version
                  tagName: ${{ github.ref_name }}
                  releaseName:
                      'Sample Release for Modern Desktop App v__VERSION__'
                  releaseBody: |
                      ${{steps.build_changelog.outputs.changelog}}
                      See the assets to download this version and install.
                  releaseDraft: false
                  prerelease: false
